apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdacs.fullname" . }}-secrets
  labels:
    {{- include "sdacs.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.env.JWT_SECRET | quote }}
  admin-password: {{ .Values.env.ADMIN_PASSWORD | quote }}
  database-url: {{ .Values.env.DATABASE_URL | quote }}
