apiVersion: v2
name: sdacs
description: Swarm Drone Airspace Control System
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - drone
  - atc
  - swarm
maintainers:
  - name: SDACS Team
