{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sdacs.fullname" . }}
  labels:
    {{- include "sdacs.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sdacs.fullname" . }}
                port:
                  number: {{ .Values.service.dashPort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "sdacs.fullname" . }}
                port:
                  number: {{ .Values.service.apiPort }}
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "sdacs.fullname" . }}
                port:
                  number: {{ .Values.service.apiPort }}
{{- end }}
