{{- if not .Values.timescaledb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdacs.fullname" . }}-secret
  labels:
    {{- include "sdacs.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.timescaledb.password | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-timescaledb:%d/%s" .Values.timescaledb.user .Values.timescaledb.password (include "sdacs.fullname" .) (.Values.timescaledb.port | int) .Values.timescaledb.database | quote }}
  jwt-secret: {{ randAlphaNum 32 | quote }}
{{- end }}
