{{- if .Values.secretEnv.SDACS_JWT_SECRET }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdacs.fullname" . }}-secret
  labels:
    {{- include "sdacs.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secretEnv.SDACS_JWT_SECRET | b64enc | quote }}
{{- end }}
