apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdacs.fullname" . }}
  labels:
    {{- include "sdacs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sdacs.selectorLabels" . | nindent 4 }}
  ports:
    - name: dash
      port: {{ .Values.service.dashPort }}
      targetPort: dash
      protocol: TCP
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
