"""SDACS Daily Status Reporter.

Checks the repository state and produces a dated Markdown report in
reports/status_YYYY-MM-DD.md.

Usage:
    python scripts/sdacs_daily_status.py [--output <path>] [--no-git]

What it checks:
  - ROADMAP.md Track A/B/C checkbox completion
  - Test file count
  - Recent git activity (last 72 hours)
  - Benchmark dataset validity
  - Open issue / PR counts (from local git remote refs if available)
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.parent
ROADMAP = ROOT / "ROADMAP.md"
TESTS_DIR = ROOT / "tests"
BENCHMARKS_SCENARIOS = ROOT / "benchmarks" / "scenarios"
REPORTS_DIR = ROOT / "reports"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(cmd, cwd=ROOT, text=True, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def _count_tests() -> int:
    return sum(1 for _ in TESTS_DIR.rglob("test_*.py")) + sum(
        1 for _ in TESTS_DIR.rglob("*_test.py")
    )


def _parse_roadmap_checkboxes() -> dict[str, dict[str, int]]:
    """Parse [x]/[ ] checkboxes per track from ROADMAP.md."""
    tracks: dict[str, dict[str, int]] = {}
    current_track = "general"

    if not ROADMAP.exists():
        return {}

    for line in ROADMAP.read_text().splitlines():
        track_match = re.search(r"Track ([A-C])", line)
        if track_match:
            current_track = f"Track {track_match.group(1)}"

        done = len(re.findall(r"- \[x\]", line, re.IGNORECASE))
        todo = len(re.findall(r"- \[ \]", line))
        if done or todo:
            t = tracks.setdefault(current_track, {"done": 0, "todo": 0})
            t["done"] += done
            t["todo"] += todo

    return tracks


def _recent_commits(hours: int = 72) -> list[str]:
    output = _run([
        "git", "log",
        f"--since={hours} hours ago",
        "--oneline",
        "--no-merges",
        "origin/main",
    ])
    if not output.strip():
        # fallback: last 5 commits
        output = _run(["git", "log", "--oneline", "-5", "origin/main"])
    return [line.strip() for line in output.splitlines() if line.strip()]


def _benchmark_status() -> tuple[int, int]:
    """Return (valid, total) scenario count."""
    total = sum(1 for d in BENCHMARKS_SCENARIOS.iterdir() if d.is_dir())
    valid = sum(
        1 for d in BENCHMARKS_SCENARIOS.iterdir()
        if d.is_dir() and (d / "manifest.yaml").exists()
    )
    return valid, total


def _open_prs_note() -> str:
    """Try to count open PRs via git remote refs; otherwise return a note."""
    refs = _run(["git", "ls-remote", "--heads", "origin"])
    pr_branches = [
        line.split()[-1]
        for line in refs.splitlines()
        if "refs/heads/claude/" in line
    ]
    if pr_branches:
        return f"{len(pr_branches)} claude/* branches in remote (check GitHub for PR status)"
    return "Unable to count open PRs locally; check GitHub"


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------

def build_report(no_git: bool = False) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = [
        f"# SDACS Daily Status — {today}",
        "",
        "> Auto-generated by `scripts/sdacs_daily_status.py`",
        "",
    ]

    # ROADMAP completion
    lines += ["## ROADMAP 완료 현황", ""]
    tracks = _parse_roadmap_checkboxes()
    if tracks:
        lines.append("| 트랙 | 완료 | 미완료 | 진행률 |")
        lines.append("|------|------|--------|--------|")
        for track, counts in sorted(tracks.items()):
            done = counts["done"]
            todo = counts["todo"]
            total_items = done + todo
            pct = f"{100 * done // total_items}%" if total_items else "—"
            lines.append(f"| {track} | {done} | {todo} | {pct} |")
    else:
        lines.append("_ROADMAP.md 파싱 실패_")
    lines.append("")

    # Benchmark status
    valid, total = _benchmark_status()
    lines += [
        "## 벤치마크 데이터셋",
        "",
        f"- 시나리오: **{valid}/{total}** 매니페스트 유효",
        f"- 스키마: `benchmarks/_schema/manifest.schema.json`",
        "",
    ]

    # Test count
    n_tests = _count_tests()
    lines += [
        "## 테스트",
        "",
        f"- 테스트 파일: **{n_tests}**개 (`tests/`)",
        "",
    ]

    # Recent git activity
    if not no_git:
        commits = _recent_commits()
        lines += ["## 최근 커밋 (최근 72h / 없으면 최근 5개)", ""]
        if commits:
            for c in commits[:10]:
                lines.append(f"- `{c}`")
        else:
            lines.append("_최근 커밋 없음_")
        lines.append("")

    # Open PRs note
    pr_note = _open_prs_note() if not no_git else "Git 비활성화됨"
    lines += [
        "## PR 현황",
        "",
        f"- {pr_note}",
        "",
    ]

    # Pending human actions
    lines += [
        "## 사람이 필요한 항목 (자동화 불가)",
        "",
        "| Phase | 항목 | 사유 |",
        "|-------|------|------|",
        "| P698-P699 | 실기 비행 시험 | 하드웨어 필요 |",
        "| P708 | 논문 내부 리뷰 3회 | 지도교수 필요 |",
        "| P709 | 공식 투고 및 arXiv | 저자 서명 필요 |",
        "| P720 | 공개 베타 오픈 | 파일럿 기관 3개 필요 |",
        "",
    ]

    lines += [
        "---",
        "",
        f"*생성 시각: {datetime.now(timezone.utc).isoformat()}*",
    ]

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SDACS daily status report")
    parser.add_argument("--output", metavar="PATH", help="Output file path")
    parser.add_argument("--no-git", action="store_true", help="Skip git commands")
    args = parser.parse_args()

    report = build_report(no_git=args.no_git)

    if args.output:
        out = Path(args.output)
    else:
        REPORTS_DIR.mkdir(exist_ok=True)
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        out = REPORTS_DIR / f"status_{today}.md"

    out.write_text(report)
    print(f"Report written to: {out}")
    print()
    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
