# config_manager.tcl - Configuration manager for SDACS drone system
# Tcl/Tk based configuration management with validation

package require Tcl 8.6

namespace eval sdacs::config {
    variable config_store [dict create]
    variable validators [dict create]
    variable schema [dict create]
    variable config_file ""
    variable version "1.2.0"
}

# Initialize default config values
proc sdacs::config::init {config_path} {
    variable config_file
    variable config_store
    variable schema

    set config_file $config_path

    # Default configuration schema
    set schema [dict create \
        "simulation.duration"     {type int    default 60   min 1 max 3600} \
        "simulation.drone_count"  {type int    default 10   min 1 max 500}  \
        "simulation.seed"         {type int    default 42   min 0 max 9999} \
        "wind.base_speed"         {type float  default 5.0  min 0.0 max 50.0} \
        "wind.direction"          {type float  default 0.0  min 0.0 max 360.0} \
        "apf.k_att"               {type float  default 1.0  min 0.1 max 10.0} \
        "apf.k_rep"               {type float  default 100.0 min 1.0 max 1000.0} \
        "apf.rep_radius"          {type float  default 30.0 min 5.0 max 200.0} \
        "api.host"                {type string default "0.0.0.0"} \
        "api.port"                {type int    default 8080 min 1024 max 65535} \
        "logging.level"           {type string default "INFO"} \
        "logging.file"            {type string default "logs/sdacs.log"} \
    ]

    # Load defaults from schema
    dict for {key spec} $schema {
        dict set config_store $key [dict get $spec default]
    }

    # Load from file if it exists
    if {[file exists $config_path]} {
        load_from_file $config_path
    }
}

# Load config from YAML-style file
proc sdacs::config::load_from_file {path} {
    variable config_store

    set fh [open $path r]
    while {[gets $fh line] >= 0} {
        set line [string trim $line]
        if {[string length $line] == 0} continue
        if {[string index $line 0] eq "#"} continue

        if {[regexp {^(\S+)\s*:\s*(.+)$} $line -> key value]} {
            set value [string trim $value]
            dict set config_store $key $value
        }
    }
    close $fh
}

# Get a config value by key
proc sdacs::config::get {key {default ""}} {
    variable config_store
    if {[dict exists $config_store $key]} {
        return [dict get $config_store $key]
    }
    return $default
}

# Set a config value with validation
proc sdacs::config::set_value {key value} {
    variable config_store
    variable schema

    if {[dict exists $schema $key]} {
        set spec [dict get $schema $key]
        set type [dict get $spec type]

        switch $type {
            "int" {
                if {![string is integer -strict $value]} {
                    error "Config '$key' requires integer value, got: $value"
                }
                set value [expr {int($value)}]
                if {[dict exists $spec min] && $value < [dict get $spec min]} {
                    error "Config '$key' value $value below minimum [dict get $spec min]"
                }
                if {[dict exists $spec max] && $value > [dict get $spec max]} {
                    error "Config '$key' value $value above maximum [dict get $spec max]"
                }
            }
            "float" {
                if {![string is double -strict $value]} {
                    error "Config '$key' requires float value, got: $value"
                }
                set value [expr {double($value)}]
            }
        }
    }

    dict set config_store $key $value
}

# Save config to file
proc sdacs::config::save {{path ""}} {
    variable config_store
    variable config_file

    if {$path eq ""} { set path $config_file }
    set fh [open $path w]
    puts $fh "# SDACS Configuration File"
    puts $fh "# Generated by config_manager.tcl"
    dict for {key value} $config_store {
        puts $fh "$key: $value"
    }
    close $fh
}

# Get all config keys matching a prefix
proc sdacs::config::get_section {prefix} {
    variable config_store
    set result [dict create]
    dict for {key value} $config_store {
        if {[string match "${prefix}*" $key]} {
            dict set result $key $value
        }
    }
    return $result
}

# Initialize with default path
sdacs::config::init "config/default_simulation.yaml"
puts "SDACS Config Manager loaded: [dict size $sdacs::config::config_store] settings"
