# Config Manager — Tcl for SDACS runtime configuration
# Phase 597

package provide sdacs_config 1.0

namespace eval sdacs::config {

    variable config_data [dict create]
    variable config_file ""
    variable watchers [list]

    # Load config from YAML-like simple key=value file
    proc load {filename} {
        variable config_data
        variable config_file

        set config_file $filename
        set config_data [dict create]

        if {![file exists $filename]} {
            return -code error "Config file not found: $filename"
        }

        set fh [open $filename r]
        while {[gets $fh line] >= 0} {
            set line [string trim $line]
            if {[string match "#*" $line] || $line eq ""} continue
            if {[regexp {^(\S+)\s*=\s*(.*)$} $line -> key val]} {
                dict set config_data $key [string trim $val]
            }
        }
        close $fh
        return $config_data
    }

    # Get config value with optional default
    proc get {key {default ""}} {
        variable config_data
        if {[dict exists $config_data $key]} {
            return [dict get $config_data $key]
        }
        return $default
    }

    # Set config value in memory
    proc set_value {key value} {
        variable config_data
        variable watchers
        set old [get $key]
        dict set config_data $key $value
        foreach watcher $watchers {
            catch {$watcher $key $old $value}
        }
    }

    # Watch for config changes
    proc watch {callback} {
        variable watchers
        lappend watchers $callback
    }

    # Save config to file
    proc save {{filename ""}} {
        variable config_data
        variable config_file

        if {$filename eq ""} { set filename $config_file }
        if {$filename eq ""} {
            return -code error "No config file set"
        }

        set fh [open $filename w]
        puts $fh "# SDACS Configuration"
        puts $fh "# Generated by sdacs::config::save"
        dict for {key val} $config_data {
            puts $fh "$key = $val"
        }
        close $fh
    }

    # List all config keys
    proc keys {} {
        variable config_data
        return [dict keys $config_data]
    }

    # Reset to defaults
    proc reset {} {
        variable config_data
        set config_data [dict create \
            drones.default_count  10 \
            simulation.hz         10 \
            separation_m          50 \
            max_speed_mps         15 \
            apf.k_attr            1.0 \
            apf.k_rep             100.0 \
            apf.d_safe            50.0 \
        ]
    }
}

# Initialize with defaults
sdacs::config::reset
