// SDACS Simulator window._sdacs TypeScript Declaration File
// 자동 생성: 2026-06-12
// 총 394개 API — 200 Phase + TRANSCENDENCE Phase 201-207 (Maturity)
// 성숙도: window._sdacs.maturityReport() 로 production/beta/mock/speculative 조회

declare global {
  interface Window { _sdacs: SDACS; }
  interface SDACS {
    /** [getter] */ readonly stats: any;
    /** [getter] */ readonly simTime: any;
    /** [getter] */ readonly simRunning: any;
    /** [getter] */ readonly droneCount: any;
    /** [getter] */ readonly weather: any;
    /** [getter] */ readonly airborne: any;
    /** [getter] */ readonly failed: any;
    /** [getter] */ readonly landed: any;
    startSim(): any;
    stopSim(): any;
    selectDrone(idOrIndex?: any): any;
    deselectDrone(): any;
    multiSelect(ids?: any): any;
    clearMulti(): any;
    /** [getter] */ readonly multiSelection: any;
    getSelected(): any;
    hoverDrone(idOrIndex?: any): any;
    clearHover(): any;
    setAnalysisView(on?: any): any;
    /** [getter] */ readonly analysisMode: any;
    /** [async] */ reportDataURL(): Promise<any>;
    /** [getter] */ readonly megaMode: any;
    /** [getter] */ readonly instanceCount: any;
    /** [getter] */ readonly visibleInstances: any;
    /** [getter] */ readonly lang: any;
    setLang(lang?: any): any;
    /** [getter] */ readonly wsConnected: any;
    /** [getter] */ readonly wsFrames: any;
    /** [getter] */ readonly liveMode: any;
    /** [getter] */ readonly perf: any;
    /** [setter] */ megaCull: any;
    /** [getter] */ readonly megaCull: any;
    /** [getter] */ readonly replayFrames: any;
    /** [getter] */ readonly dni: any;
    replaySeek(idx?: any): any;
    goLive: any;
    atcCommand(did?: any, cmd?: any, params?: any, source?: any): any;
    /** [getter] */ readonly atcLog: any;
    /** [getter] */ readonly atcControlled: any;
    setPredTrail(on?: any): any;
    /** [getter] */ readonly predTrail: any;
    setPredHorizon(s?: any): any;
    /** [getter] */ readonly predHorizon: any;
    setVelArrow(on?: any): any;
    /** [getter] */ readonly velArrow: any;
    setCpaMarker(on?: any): any;
    /** [getter] */ readonly cpaMarker: any;
    /** [getter] */ readonly cpaPairsCount: any;
    setSunCycle(on?: any): any;
    setSunHour(h?: any): any;
    setSunAuto(on?: any): any;
    /** [getter] */ readonly sunHour: any;
    /** [getter] */ readonly sunEnabled: any;
    setRain(on?: any, intensity?: any): any;
    setSnow(on?: any, intensity?: any): any;
    startRecording(): any;
    stopRecording(): any;
    /** [getter] */ readonly recording: any;
    injectFault(droneId?: any, type?: any, opts?: any): any;
    injectRogue(): any;
    injectDynamicNFZ(x?: any, z?: any, r?: any, dur?: any): any;
    injectScenario(name?: any): any;
    injClearAll(): any;
    /** [getter] */ readonly injStats: any;
    /** [getter] */ readonly dynamicNfzList: any;
    setCamMode(mode?: any): any;
    /** [getter] */ readonly camMode: any;
    focusDrone(idOrIndex?: any): any;
    setAmbientAudio(on?: any): any;
    /** [getter] */ readonly ambientAudio: any;
    missionAdd(droneId?: any, waypoints?: any, templateName?: any): any;
    missionTemplate(name?: any, originX?: any, originZ?: any): any;
    missionAssignTemplate(droneId?: any, templateName?: any): any;
    missionClearAll(): any;
    /** [getter] */ readonly missions: any;
    setAnaHeatmap(on?: any): any;
    /** [getter] */ readonly anaHeatmap: any;
    /** [getter] */ readonly anaKpiWindow: any;
    exportLatexKpi(): any;
    /** [getter] */ readonly isMobile: any;
    /** [getter] */ readonly mobileLOD: any;
    applyMobileLOD(): any;
    openGallery(): any;
    closeGallery(): any;
    /** [getter] */ readonly galleryOpen: any;
    /** [getter] */ readonly scenarioCategories: any;
    /** [getter] */ readonly availableLangs: any;
    /** [getter] */ readonly xrSupported: any;
    /** [getter] */ readonly xrPresenting: any;
    exportMission(): any;
    importMission(jsonText?: any): any;
    triggerMissionImport(): any;
    copilotPlan(prompt?: any): any;
    copilotExecute(plan?: any): any;
    /** [getter] */ readonly copilotHistory: any;
    spawnAdversarial(policy?: any): any;
    clearAdversarial(): any;
    /** [getter] */ readonly adversarialPolicy: any;
    /** [getter] */ readonly adversarialDrones: any;
    /** [getter] */ readonly adversarialSafetyResponse: any;
    /** [getter] */ readonly adversarialPolicies: any;
    startChoreography(pattern?: any): any;
    clearChoreography(): any;
    /** [getter] */ readonly choreoPattern: any;
    /** [getter] */ readonly choreoPatterns: any;
    enableCuas(on?: any): any;
    setCuasMode(m?: any): any;
    cuasEngage(): any;
    cuasDetect(): any;
    /** [getter] */ readonly cuasEnabled: any;
    /** [getter] */ readonly cuasMode: any;
    /** [getter] */ readonly cuasEngagements: any;
    /** [getter] */ readonly cuasLog: any;
    /** [getter] */ readonly cuasModes: any;
    enableWindField(on?: any): any;
    setWindRegime(name?: any): any;
    sampleWindAt(wx?: any, wz?: any): any;
    /** [getter] */ readonly windFieldEnabled: any;
    /** [getter] */ readonly windRegime: any;
    /** [getter] */ readonly windFieldStats: any;
    enableGpu50k(on?: any): any;
    gpu50kBuild(): any;
    gpu50kQuery(idx?: any, radius?: any): any;
    /** [getter] */ readonly gpu50kEnabled: any;
    /** [getter] */ readonly gpu50kStats: any;
    enableCrdt(on?: any): any;
    crdtAddOp(target?: any, cmd?: any, params?: any): any;
    crdtMerge(remoteOps?: any): any;
    crdtSnapshot(): any;
    /** [getter] */ readonly crdtEnabled: any;
    /** [getter] */ readonly crdtSiteId: any;
    enableDtwin(on?: any): any;
    dtwinDecodeGPI(buf?: any): any;
    dtwinApplyGPI(payload?: any, idx?: any): any;
    dtwinSetOrigin(lat?: any, lon?: any): any;
    /** [getter] */ readonly dtwinEnabled: any;
    /** [getter] */ readonly dtwinStats: any;
    notamAdd(entry?: any): any;
    notamImportJson(text?: any): any;
    /** [getter] */ readonly notams: any;
    /** [getter] */ readonly notamCount: any;
    /** [getter] */ readonly batteryAgeStats: any;
    arEnter(): any;
    arExit(): any;
    arAddPin(lat?: any, lon?: any, label?: any): any;
    arClearPins(): any;
    /** [getter] */ readonly arEnabled: any;
    /** [getter] */ readonly arPins: any;
    enableAcoustic(on?: any): any;
    acousticAddObserver(x?: any, z?: any, label?: any): any;
    /** [getter] */ readonly acousticEnabled: any;
    /** [getter] */ readonly acousticObservers: any;
    /** [getter] */ readonly acousticStats: any;
    generateForecast(hours?: any): any;
    forecastQueryHour(h?: any): any;
    forecastFlyableHours(windMax?: any, precipMax?: any): any;
    /** [getter] */ readonly forecastData: any;
    utmFederationAdd(id?: any, label?: any, region?: any): any;
    utmFederationHandoff(droneId?: any, fromUtm?: any, toUtm?: any): any;
    utmFederationSync(): any;
    /** [getter] */ readonly utmFederationInstances: any;
    /** [getter] */ readonly utmFederationHandoffLog: any;
    enablePqc(on?: any): any;
    /** [getter] */ readonly pqcStats: any;
    /** [getter] */ readonly pqcEnabled: any;
    satelliteInit(name?: any): any;
    satelliteVisibleAt(lat?: any, lon?: any): any;
    satelliteHandoff(): any;
    /** [getter] */ readonly satelliteConstellation: any;
    /** [getter] */ readonly satelliteCount: any;
    uuvAdd(x?: any, z?: any, depth?: any): any;
    uuvAcousticBudget(): any;
    /** [getter] */ readonly uuvVehicles: any;
    sensorFusionToggle(sensor?: any, on?: any): any;
    sensorFusionSetFilter(name?: any): any;
    sensorFusionEffectiveNoise(): any;
    /** [getter] */ readonly sensorFusionState: any;
    mecAdd(x?: any, z?: any, cap?: any, lat?: any): any;
    mecAssign(droneId?: any, sizeKB?: any): any;
    /** [getter] */ readonly mecNodes: any;
    /** [getter] */ readonly mecWorkloads: any;
    fedLearnRound(n?: any, loss?: any): any;
    /** [getter] */ readonly fedLearnState: any;
    /** [getter] */ readonly fedLearnHistory: any;
    ugvAdd(x?: any, z?: any, label?: any): any;
    multiDomainHandoff(droneId?: any, fromD?: any, toD?: any, missionId?: any): any;
    /** [getter] */ readonly ugvs: any;
    /** [getter] */ readonly multiDomainHandoffLog: any;
    audioDopplerShift(droneIdx?: any, freq?: any): any;
    audioSetListener(x?: any, z?: any): any;
    /** [getter] */ readonly audioEngineState: any;
    photogrammetryImport(name?: any, bboxKm?: any, url?: any): any;
    /** [getter] */ readonly photogrammetryScenes: any;
    esportsAddPlayer(name?: any, role?: any): any;
    esportsScore(playerId?: any, delta?: any): any;
    /** [getter] */ readonly esportsPlayers: any;
    procCityGenerate(sizeKm?: any, density?: any): any;
    /** [getter] */ readonly procCityBuildingCount: any;
    eyeTrackAdd(x?: any, y?: any): any;
    eyeTrackBuildHeatmap(): any;
    /** [getter] */ readonly eyeTrackPointCount: any;
    voiceMacroDefine(name?: any, ops?: any): any;
    voiceMacroExecute(name?: any): any;
    /** [getter] */ readonly voiceMacros: any;
    timeCompressSet(f?: any): any;
    timeCompressReset(): any;
    hitlAdd(id?: any, label?: any): any;
    hitlConnect(id?: any): any;
    /** [getter] */ readonly hitlNodes: any;
    nationalASInitKorea(): any;
    nationalASAddAirport(icao?: any, lat?: any, lon?: any, name?: any): any;
    /** [getter] */ readonly nationalASAirports: any;
    enableClimate(on?: any): any;
    /** [getter] */ readonly climateScore: any;
    crossBorderTransit(droneId?: any, fromC?: any, toC?: any, approved?: any): any;
    /** [getter] */ readonly crossBorderTransitsLog: any;
    planetarySetBody(name?: any): any;
    /** [getter] */ readonly planetaryState: any;
    publicDemoLeaderboardAdd(name?: any, score?: any): any;
    publicDemoDailyChallenge(): any;
    /** [getter] */ readonly publicDemoLeaderboard: any;
    stellar51DelegateGroup(droneIds?: any, llmProvider?: any): any;
    stellar51Recommend(droneId?: any): any;
    stellar51Tick(): any;
    stellar51Revoke(groupId?: any): any;
    /** [getter] */ readonly stellar51Groups: any;
    rlhfFeedback(decision?: any, rating?: any, notes?: any): any;
    /** [getter] */ readonly rlhfState: any;
    causalAddEdge(from?: any, to?: any, weight?: any): any;
    causalDoQuery(intervention?: any, target?: any): any;
    /** [getter] */ readonly causalDag: any;
    adversarialCheck(input?: any): any;
    /** [getter] */ readonly adversarialDetected: any;
    explainDecision(decision?: any, features?: any): any;
    /** [getter] */ readonly explainLastMethod: any;
    gpu100kInit(): any;
    /** [getter] */ readonly gpu100kStats: any;
    distributedSimAddShard(s?: any, e?: any): any;
    distributedSimRebalance(): any;
    /** [getter] */ readonly distributedShards: any;
    cloudBurstScale(load?: any): any;
    /** [getter] */ readonly cloudBurstState: any;
    streamingReplayPush(frame?: any): any;
    /** [getter] */ readonly streamingStats: any;
    videoProcEncode(frame?: any): any;
    /** [getter] */ readonly videoProcStats: any;
    skybrushConnect(addr?: any): any;
    /** [getter] */ readonly skybrushConnected: any;
    cesiumGlobalInit(): any;
    /** [getter] */ readonly cesiumGlobalState: any;
    ue5ExportScene(name?: any): any;
    /** [getter] */ readonly ue5SceneCount: any;
    ros2SubscribeTopic(name?: any, msgType?: any): any;
    /** [getter] */ readonly ros2Topics: any;
    isaacSimLoadUSD(url?: any): any;
    /** [getter] */ readonly isaacSimState: any;
    societyAddReport(cat?: any, sev?: any): any;
    societyInsuranceQuote(role?: any, hours?: any, history?: any): any;
    /** [getter] */ readonly societyReports: any;
    /** [getter] */ readonly societyInsurancePrices: any;
    beyondEarthSetMode(m?: any): any;
    beyondEarthAddDebris(altKm?: any, sizeM?: any): any;
    /** [getter] */ readonly beyondEarthState: any;
    qkdExchangeKey(bits?: any): any;
    annealingSolve(size?: any): any;
    /** [getter] */ readonly quantumState: any;
    bciActivate(channels?: any): any;
    olfactorySpray(scent?: any): any;
    /** [getter] */ readonly xrFrontierState: any;
    uamPriceQuote(distKm?: any, demand?: any): any;
    daoCreateProposal(title?: any, desc?: any): any;
    /** [getter] */ readonly economyState: any;
    ultimateExpandCoverage(pct?: any): any;
    ultimateUnProposal(title?: any): any;
    /** [getter] */ readonly ultimateState: any;
    singularitySelfImprove(): any;
    singularityMetaverseConnect(platform?: any): any;
    singularityStdProposal(name?: any): any;
    /** [getter] */ readonly singularityState: any;
    petaflop101Activate(tflops?: any): any;
    quantum102Hash(n?: any): any;
    photonic103Init(wavelengths?: any): any;
    optane104Snapshot(): any;
    rdma105AddHost(addr?: any, gbps?: any): any;
    fpga106AddInstance(): any;
    tpu107Inference(model?: any, sz?: any): any;
    neuromorphic108Spike(rate?: any): any;
    dpu109Offload(bytes?: any): any;
    megaScale110SetCurrent(n?: any): any;
    /** [getter] */ readonly ultimate101_110Stats: any;
    nano111Spawn(n?: any): any;
    smartDust112Deploy(n?: any): any;
    graphene113Boost(f?: any): any;
    selfHeal114Cycle(): any;
    bioDeg115SetLife(h?: any): any;
    atmo116Harvest(j?: any): any;
    piezo117Generate(w?: any): any;
    solar118SetEff(e?: any): any;
    meta119Activate(on?: any): any;
    progMatter120Reshape(s?: any): any;
    neuron121Connect(hz?: any): any;
    dna122Store(gb?: any): any;
    bacteria123Spawn(n?: any): any;
    algae124Power(w?: any): any;
    mycelium125Repair(): any;
    bird126Partner(sp?: any): any;
    insect127Join(n?: any): any;
    symbiotic128Bond(d?: any, a?: any): any;
    biofluor129Emit(c?: any): any;
    living130Spawn(g?: any): any;
    rfc131Submit(t?: any): any;
    icao132Adopt(): any;
    iso133Cert(num?: any): any;
    ieee134Standard(name?: any): any;
    itu135AllocateFreq(mhz?: any): any;
    un136Resolution(): any;
    easa137Integrate(): any;
    faa138Part108(): any;
    caac139Compat(): any;
    global140Adopt(pct?: any): any;
    selfAware141Activate(): any;
    recursion142Sim(): any;
    consciousness143Experiment(): any;
    realityBlur144Set(l?: any): any;
    translator145Add(): any;
    eternalMission146Start(): any;
    timeLoop147Iterate(): any;
    parallel148Universe(): any;
    toe149Unify(): any;
    universeOS150Deploy(): any;
    /** [getter] */ readonly ultimate111_150Stats: any;
    p151Galactic(n?: any): any;
    p152DarkMatter(): any;
    p153Pulsar(name?: any): any;
    p154Wormhole(from?: any, to?: any): any;
    p155GravWave(): any;
    p156Antimatter(kg?: any): any;
    p157BlackHole(mass?: any): any;
    p158CosmicRayShield(n?: any): any;
    p159Interstellar(packets?: any): any;
    p160GalacticCoverage(ly?: any): any;
    p161Retrocausal(): any;
    p162CausalityLoop(): any;
    p163Tachyon(): any;
    p164BlockUniverse(): any;
    p165SpacetimeEdit(): any;
    p166CollapseCtrl(): any;
    p167QuantumEraser(): any;
    p168Decoherence(): any;
    p169TimelineBranch(name?: any): any;
    p170RealityEdit(): any;
    p171DigitalHuman(name?: any): any;
    p172MindUpload(): any;
    p173MemoryEncode(tb?: any): any;
    p174DreamShare(): any;
    p175Telepathy(a?: any, b?: any): any;
    p176Empathy(s?: any): any;
    p177FreeWillSample(): any;
    p178PersonalityTransfer(): any;
    p179SoulContinuity(): any;
    p180ConsciousDrone(): any;
    p181HeatDeath(): any;
    p182EntropyReverse(n?: any): any;
    p183InfoPreserve(): any;
    p184BoltzmannPrevent(): any;
    p185SimHypothesis(): any;
    p186VacuumShield(): any;
    p187StrangeletContain(n?: any): any;
    p188GreyGooMitigate(): any;
    p189PaperclipPrevent(): any;
    p190ExistRisk(l?: any): any;
    p191BeyondMath(): any;
    p192BeyondLogic(): any;
    p193BeyondPhysics(): any;
    p194BeyondComputation(): any;
    p195BeyondTime(): any;
    p196BeyondSpace(): any;
    p197BeyondExistence(): any;
    p198PureInformation(): any;
    p199UniversalIdentity(): any;
    p200UnityAchieved(): any;
    /** [getter] */ readonly postUniverseStats: any;
    setAtcAudio(on?: any): any;
    /** [getter] */ readonly atcAudio: any;
    clearAllAtc(): any;
    selectScenario(name?: any): any;
    setLayer(name?: any, on?: any): any;
    /** [getter] */ readonly layers: any;
    /** [getter] */ readonly conflictPairs: any;
    /** [getter] */ readonly replay: any;
    replayStep(delta = 1?: any): any;
    captureScreenshot(): any;
    apiMaturity(name?: any): any;
    maturityReport(): any;
  }
}

export {};