apiVersion: v1
kind: Secret
metadata:
  name: sdacs-secret
  labels:
    {{- include "sdacs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
