apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sdacs
  labels:
    app: {{ .Release.Name }}-sdacs
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashPort }}
      targetPort: dash
      name: dash
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      name: api
  selector:
    app: {{ .Release.Name }}-sdacs
